### ISSUE TITLE
fold this into ACCIDDA/longleaf-setup

### ISSUE THREAD

**Issue by pearsonca** [UNCIDD/Ressources#1]
This seems to be superceded by ACCIDDA/longleaf-setup - how about PR anything we wish to preserve from this into that, then :fire: this?

**Comment by jcblemai** [comment]
Thanks @pearsonca, this has been moved to ACCIDDA KeyDocsAndDiscussion following discussion with justin. If that is good for you let me know and I'll delete this repository

**Comment by pearsonca** [comment]
Works for me, thanks!
